<?xml version="1.0" encoding="utf-8"?><Database Name="ShelterDatabase" Class="ShelterDatabaseLINQDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\Database\ShelterDatabase.mdf;Integrated Security=True;Connect Timeout=30" SettingsObjectName="ShelterEvidency.Properties.Settings" SettingsPropertyName="ShelterDatabaseConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Adoptions" Member="Adoptions">
    <Type Name="Adoptions">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AnimalID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PersonID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Adresses" Member="Adresses">
    <Type Name="Adresses">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="City" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Street" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PersonID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Zip" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Animals" Member="Animals">
    <Type Name="Animals">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ChipNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Birth" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SexID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SpeciesID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BreedID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CoatTypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FurColorID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="VetID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OwnerID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NewOwnerID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FeedRation" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CrossBreedID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Breeds_Animals" Member="Breeds" ThisKey="BreedID" OtherKey="Id" Type="Breeds" IsForeignKey="true" />
      <Association Name="Breeds_Animals1" Member="Breeds1" ThisKey="CrossBreedID" OtherKey="Id" Type="Breeds" IsForeignKey="true" />
      <Association Name="CoatTypes_Animals" Member="CoatTypes" ThisKey="CoatTypeID" OtherKey="Id" Type="CoatTypes" IsForeignKey="true" />
      <Association Name="FurColors_Animals" Member="FurColors" ThisKey="FurColorID" OtherKey="Id" Type="FurColors" IsForeignKey="true" />
      <Association Name="People_Animals" Member="People" ThisKey="NewOwnerID" OtherKey="Id" Type="People" IsForeignKey="true" />
      <Association Name="People_Animals1" Member="People1" ThisKey="OwnerID" OtherKey="Id" Type="People" IsForeignKey="true" />
      <Association Name="People_Animals2" Member="People2" ThisKey="VetID" OtherKey="Id" Type="People" IsForeignKey="true" />
      <Association Name="Sexes_Animals" Member="Sexes" ThisKey="SexID" OtherKey="Id" Type="Sexes" IsForeignKey="true" />
      <Association Name="Species_Animals" Member="Species" ThisKey="SpeciesID" OtherKey="Id" Type="Species" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Breeds" Member="Breeds">
    <Type Name="Breeds">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BreedName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SpeciesID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Breeds_Animals" Member="Animals" ThisKey="Id" OtherKey="BreedID" Type="Animals" />
      <Association Name="Breeds_Animals1" Member="Animals1" ThisKey="Id" OtherKey="CrossBreedID" Type="Animals" />
    </Type>
  </Table>
  <Table Name="dbo.CoatTypes" Member="CoatTypes">
    <Type Name="CoatTypes">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CoatTypeName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="CoatTypes_Animals" Member="Animals" ThisKey="Id" OtherKey="CoatTypeID" Type="Animals" />
    </Type>
  </Table>
  <Table Name="dbo.Costs" Member="Costs">
    <Type Name="Costs">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CostName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Price" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AnimalID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Deaths" Member="Deaths">
    <Type Name="Deaths">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DeathTypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AnimalID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Descriprion" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DeathTypes" Member="DeathTypes">
    <Type Name="DeathTypes">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DeathTypeName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Donations" Member="Donations">
    <Type Name="Donations">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DonatorID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Amount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DonationName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.EndTypes" Member="EndTypes">
    <Type Name="EndTypes">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Descritption" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="EndTypeName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.FurColors" Member="FurColors">
    <Type Name="FurColors">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FurColorName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="FurColors_Animals" Member="Animals" ThisKey="Id" OtherKey="FurColorID" Type="Animals" />
    </Type>
  </Table>
  <Table Name="dbo.Images" Member="Images">
    <Type Name="Images">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AnimalID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ImagePath" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Incidents" Member="Incidents">
    <Type Name="Incidents">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IncidentDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IncidentTypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AnimalID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.IncidentTypes" Member="IncidentTypes">
    <Type Name="IncidentTypes">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IncidentTypeName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Severity" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MedicalRecords" Member="MedicalRecords">
    <Type Name="MedicalRecords">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RecordName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CostID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AnimalID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="VetID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.People" Member="People">
    <Type Name="People">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RoleID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Mail" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Association Name="People_Animals" Member="Animals" ThisKey="Id" OtherKey="NewOwnerID" Type="Animals" />
      <Association Name="People_Animals1" Member="Animals1" ThisKey="Id" OtherKey="OwnerID" Type="Animals" />
      <Association Name="People_Animals2" Member="Animals2" ThisKey="Id" OtherKey="VetID" Type="Animals" />
    </Type>
  </Table>
  <Table Name="dbo.Roles" Member="Roles">
    <Type Name="Roles">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RoleName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Sexes" Member="Sexes">
    <Type Name="Sexes">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SexName" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Association Name="Sexes_Animals" Member="Animals" ThisKey="Id" OtherKey="SexID" Type="Animals" />
    </Type>
  </Table>
  <Table Name="dbo.Species" Member="Species">
    <Type Name="Species">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SpeciesName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Species_Animals" Member="Animals" ThisKey="Id" OtherKey="SpeciesID" Type="Animals" />
    </Type>
  </Table>
  <Table Name="dbo.Stays" Member="Stays">
    <Type Name="Stays">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FinishDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AnimalID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EndTypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Walks" Member="Walks">
    <Type Name="Walks">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Start" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="[End]" Member="End" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AnimalID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PersonID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>